rootProject.name = "arkivo"

include(
    "arkivo-archive",
    "arkivo-codec",
    "arkivo-codec-all",
    "arkivo-codec-gzip",
    "arkivo-codec-zlib",
    "arkivo-codec-deflate",
    "arkivo-codec-deflate64",
    "arkivo-codec-bcj",
    "arkivo-codec-delta",
    "arkivo-codec-bzip2",
    "arkivo-codec-xz",
    "arkivo-codec-lzma",
    "arkivo-codec-ppmd",
    "arkivo-codec-zstd",
    "arkivo-archive-all",
    "arkivo-archive-ar",
    "arkivo-archive-rar",
    "arkivo-archive-tar",
    "arkivo-archive-zip",
    "arkivo-archive-7z",
    "arkivo-all",
)
