rootProject.name = "arkivo"

include(
    "arkivo-base",
    "arkivo-archive",
    "arkivo-codec",
    "arkivo-codec-all",
    "arkivo-codec-compress",
    "arkivo-codec-deflate",
    "arkivo-codec-bzip2",
    "arkivo-codec-xz",
    "arkivo-codec-lzma",
    "arkivo-codec-lzip",
    "arkivo-codec-lz4",
    "arkivo-codec-ppmd",
    "arkivo-codec-zstd",
    "arkivo-archive-all",
    "arkivo-archive-ar",
    "arkivo-archive-cpio",
    "arkivo-archive-rar",
    "arkivo-archive-tar",
    "arkivo-archive-zip",
    "arkivo-archive-7z",
    "arkivo-all",
)
