upstream=apache/commons-compress
version=1.28.0
archiveRoot=commons-compress-1.28.0-src
archiveName=commons-compress-1.28.0-src.tar.gz
archiveUrl=https://archive.apache.org/dist/commons/compress/source/commons-compress-1.28.0-src.tar.gz
archiveSize=61394705
archiveSha256=5c870fa454221b24c81d10a28031a9183d55f2baab92c160ecc985e51a387662
resourceFileCount=353
resourceTotalSize=96228477
license=Apache-2.0
