upstream=apache/commons-compress
version=1.28.0
revision=852d9c23b94127feafc1649d9c7f13d4df338845
baseUrl=https://raw.githubusercontent.com/apache/commons-compress/852d9c23b94127feafc1649d9c7f13d4df338845/
license=Apache-2.0
files=license,notice,blaTar,rawDeflate,zlib,gzipMembers,gzipEmptyMembers,deflate64Input,deflate64Archive,deflate64DataDescriptorArchive,deflate64ReadBeyondMemoryArchive
file.license.path=LICENSE.txt
file.license.size=11358
file.license.sha256=51b88fd3e9e24edcdce1dd145a4fca2dcd12911407f00b06dfa6ff600f9733c1
file.notice.path=NOTICE.txt
file.notice.size=178
file.notice.sha256=0d98967f0ab328af8d9d536aa9a5c684b5dd665657245f6ee6b5915affe811c0
file.blaTar.path=src/test/resources/bla.tar
file.blaTar.size=10240
file.blaTar.sha256=8e081a961b6a97f68e19cf6e26f3b85e04ffef27dbe9c4ad664d79a7ced06a38
file.rawDeflate.path=src/test/resources/bla.tar.deflate
file.rawDeflate.size=462
file.rawDeflate.sha256=8030883fc3663aa04715fe5a6dee19d1d46157a4438cdfc0a3fd1a34f4f4fbfd
file.zlib.path=src/test/resources/bla.tar.deflatez
file.zlib.size=468
file.zlib.sha256=94f7e82a678084ddb8da9e47a188ca698ebf169b8ff539366febcec99dcfde0b
file.gzipMembers.path=src/test/resources/org/apache/commons/compress/gzip/members.gz
file.gzipMembers.size=76
file.gzipMembers.sha256=752fef168bdef584762c7ad572bfeb0d6d9d0d15cdf105a41c09f6c9cd3e1d61
file.gzipEmptyMembers.path=src/test/resources/org/apache/commons/compress/gzip/members-size-0.gz
file.gzipEmptyMembers.size=117
file.gzipEmptyMembers.sha256=bfea4d9e36e5574ca814b0d06694c6591e8595239642419be0f34df32747464e
file.deflate64Input.path=src/test/resources/COMPRESS-380/COMPRESS-380-input
file.deflate64Input.size=3072
file.deflate64Input.sha256=232ac641bd1b38108e7625d65b69286ccaac1b42c743d079656d613e641217dc
file.deflate64Archive.path=src/test/resources/COMPRESS-380/COMPRESS-380.zip
file.deflate64Archive.size=2257
file.deflate64Archive.sha256=0e4828fea4ec9086456131e3122a9f71d5cc1988a5102beb109236cdb276e867
file.deflate64DataDescriptorArchive.path=src/test/resources/COMPRESS-380/COMPRESS-380-dd.zip
file.deflate64DataDescriptorArchive.size=1391
file.deflate64DataDescriptorArchive.sha256=f5239c89e6ba0fad7269b468d7a66eacbc4ecd781df4f5ce5b80680e8a22b800
file.deflate64ReadBeyondMemoryArchive.path=src/test/resources/COMPRESS-380/COMPRESS-380-readbeyondmemory.zip
file.deflate64ReadBeyondMemoryArchive.size=15290
file.deflate64ReadBeyondMemoryArchive.sha256=e8578ec3aaa27fcbdd0aa93a5e9562aedde7fdcfcede0258ed25b019eb5b66c7
