upstream=python/cpython
version=3.14.0
archiveRoot=cpython-3.14.0
archiveName=cpython-3.14.0.tar.gz
archiveUrl=https://codeload.github.com/python/cpython/tar.gz/refs/tags/v3.14.0
archiveSize=31151111
archiveSha256=703f51b3c79eeb0c31c044de10c0bdf3e45db86c495e13f735cd3afa01f650ab
license=PSF-2.0
