upstream=dotnet/runtime
version=10.0.0
archiveRoot=runtime-10.0.0
archiveName=runtime-10.0.0.tar.gz
archiveUrl=https://codeload.github.com/dotnet/runtime/tar.gz/refs/tags/v10.0.0
archiveSize=94941979
archiveSha256=cbc351c6f7afa4fcb622c8faf09f2371933fbd1413672556a410e3bfff061ddf
license=MIT
