upstream=101arrowz/fflate
version=0.8.3
archiveRoot=package
archiveName=fflate-0.8.3.tgz
archiveUrl=https://registry.npmjs.org/fflate/-/fflate-0.8.3.tgz
archiveSize=173034
archiveSha256=38c2cd824402407b43153c782274aec2ea83ea688e4aa0b743c5f2c305857d92
license=MIT
