upstream=GNU cpio
version=2.15
archiveRoot=cpio-2.15
archiveName=cpio-2.15.tar.gz
archiveUrl=https://ftp.gnu.org/gnu/cpio/cpio-2.15.tar.gz
archiveSize=2277589
archiveSha256=efa50ef983137eefc0a02fdb51509d624b5e3295c980aa127ceee4183455499e
license=GPL-3.0-or-later
