upstream=Stuk/jszip
version=3.10.1
archiveRoot=jszip-3.10.1
archiveName=jszip-3.10.1.tar.gz
archiveUrl=https://codeload.github.com/Stuk/jszip/tar.gz/refs/tags/v3.10.1
archiveSize=23079881
archiveSha256=e873e5d0d8549c78c0eafcab8fba40f4a1e27c5a9d48f4a6b2eb122470d0d88c
license=MIT
