upstream=klauspost/compress
version=1.18.0
archiveRoot=compress-1.18.0
archiveName=compress-1.18.0.tar.gz
archiveUrl=https://codeload.github.com/klauspost/compress/tar.gz/refs/tags/v1.18.0
archiveSize=39078330
archiveSha256=2fdacf413615dc72f8cb4d199ce49bb5591da7ebdefaf7e2d1acf50ba2246c6c
license=BSD-3-Clause
