upstream=libarchive/libarchive
version=3.8.7
archiveRoot=libarchive-3.8.7
archiveName=libarchive-3.8.7.tar.gz
archiveUrl=https://github.com/libarchive/libarchive/releases/download/v3.8.7/libarchive-3.8.7.tar.gz
archiveSize=8560199
archiveSha256=4b787cca6697a95c7725e45293c973c208cbdc71ae2279f30ef09f52472b9166
license=BSD-2-Clause
