upstream=ebiggers/libdeflate
version=1.26
archiveRoot=libdeflate-1.26
archiveName=libdeflate-1.26.tar.gz
archiveUrl=https://codeload.github.com/ebiggers/libdeflate/tar.gz/refs/tags/v1.26
archiveSize=198768
archiveSha256=bba03fffc5538576213675ce6968fcff6ce2e67d82e4d5febea2d05f9f13cf85
license=MIT
