upstream=lz4/lz4-java
version=1.8.0
archiveRoot=lz4-java-1.8.0
archiveName=lz4-java-1.8.0.tar.gz
archiveUrl=https://github.com/lz4/lz4-java/archive/refs/tags/1.8.0.tar.gz
archiveSize=1069398
archiveSha256=c4a49548ce66e4db1c208a92e5320ac61ce26e7490b79cfb813c06269676705c
resourceFileCount=4
resourceTotalSize=1384472
license=Apache-2.0
