upstream=savannah/lzip
version=1.26
archiveRoot=lzip-1.26
archiveName=lzip-1.26.tar.gz
archiveUrl=https://download-mirror.savannah.gnu.org/releases/lzip/lzip-1.26.tar.gz
archiveSize=120476
archiveSha256=641cf30961525cbe3b340cc883436c8854e9f5032f459f444de4782b621e6572
license=GPL-2.0-or-later
