upstream=icsharpcode/SharpZipLib
version=1.4.2
revision=33f64eb0f28cdd2b084cb822fcc224c7c5aba553
archiveRoot=SharpZipLib-1.4.2
archiveName=SharpZipLib-1.4.2.tar.gz
archiveUrl=https://codeload.github.com/icsharpcode/SharpZipLib/tar.gz/refs/tags/v1.4.2
archiveSize=2104712
archiveSha256=92678f2b5e4ec2ca6df598ef6d3bbf57f0176ada2e4901f689d844f7744fe9c6
license=MIT
