upstream=tukaani-project/xz
version=5.8.3
archiveRoot=xz-5.8.3
archiveName=xz-5.8.3.tar.gz
archiveUrl=https://github.com/tukaani-project/xz/releases/download/v5.8.3/xz-5.8.3.tar.gz
archiveSize=2771455
archiveSha256=3d3a1b973af218114f4f889bbaa2f4c037deaae0c8e815eec381c3d546b974a0
license=0BSD
