upstream=zip-rs/zip2
version=8.6.0
archiveRoot=zip2-8.6.0
archiveName=zip2-8.6.0.tar.gz
archiveUrl=https://codeload.github.com/zip-rs/zip2/tar.gz/refs/tags/v8.6.0
archiveSize=55892335
archiveSha256=205300e25bb43b769dbb5dd4fd477413cf62f48b70100300ed1d1aeeb3ab51f4
license=MIT
