upstream=madler/zlib
version=1.3.1
archiveRoot=zlib-1.3.1
archiveName=zlib-1.3.1.tar.gz
archiveUrl=https://zlib.net/fossils/zlib-1.3.1.tar.gz
archiveSize=1512791
archiveSha256=9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
license=Zlib
