upstream=zlib-ng/zlib-ng
version=2.3.2
archiveRoot=zlib-ng-2.3.2
archiveName=zlib-ng-2.3.2.tar.gz
archiveUrl=https://codeload.github.com/zlib-ng/zlib-ng/tar.gz/refs/tags/2.3.2
archiveSize=2446623
archiveSha256=6a0561b50b8f5f6434a6a9e667a67026f2b2064a1ffa959c6b2dae320161c2a8
license=Zlib
