upstream=Zopfli
version=zopfli-1.0.3
archiveRoot=zopfli-zopfli-1.0.3
archiveName=zopfli-1.0.3.tar.gz
archiveUrl=https://codeload.github.com/google/zopfli/tar.gz/refs/tags/zopfli-1.0.3
archiveSize=195227
archiveSha256=e955a7739f71af37ef3349c4fa141c648e8775bceb2195be07e86f8e638814bd
license=Apache-2.0
