upstream=facebook/zstd
version=1.5.7
archiveRoot=zstd-1.5.7
archiveName=zstd-1.5.7.tar.gz
archiveUrl=https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz
archiveSize=2434947
archiveSha256=eb33e51f49a15e023950cd7825ca74a4a2b43db8354825ac24fc1b7ee09e6fa3
license=BSD-3-Clause OR GPL-2.0-only
