// Copyright (c) 2026 Glavo
// SPDX-License-Identifier: MPL-2.0

package org.glavo.arkivo.codec.zstd;

import com.github.luben.zstd.ZstdDecompressCtx;
import org.glavo.arkivo.codec.CodecOutcome;
import org.glavo.arkivo.codec.CompressionCodec;
import org.glavo.arkivo.codec.CompressionDecoder;
import org.glavo.arkivo.internal.ByteArrayAccess;
import org.jetbrains.annotations.NotNullByDefault;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.Unmodifiable;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/// Verifies frames and matching plaintext generated by Zstandard 1.5.7's unmodified decodecorpus tool.
///
/// Set `ARKIVO_ZSTD_DECODECORPUS_EXECUTABLE` to a generator built from the verified reference sources. Set
/// `ARKIVO_REQUIRE_ZSTD_DECODECORPUS=true` to fail, rather than skip, when it is absent. Seeds and options are
/// included in invocation diagnostics. Native code is used only to generate and independently verify test data.
@NotNullByDefault
final class ZstdDecodeCorpusTest {
    /// The number of paired frames produced by each deterministic invocation.
    private static final int FRAME_COUNT = 16;

    /// A codec bounded above the generator's documented window and content limits.
    private static final ZstdCodec CODEC = new ZstdCodec().withMaximumOutputSize(1L << 20)
            .withMaximumWindowSize(1L << 23).withMaximumMemorySize(1L << 26);

    /// Stores generated pairs, dictionaries, and native diagnostics outside the source tree.
    @TempDir
    Path directory;

    /// Combines automatic and forced encodings with two fixed random sequences.
    private static Stream<Arguments> configurations() {
        return Stream.of(
                new Mode("mixed", List.of()),
                new Mode("content-size", List.of("--content-size")),
                new Mode("small-blocks", List.of("--max-block-size-log=8")),
                new Mode("large-frames", List.of("--max-content-size-log=20")),
                new Mode("raw", List.of("--block-type=0")),
                new Mode("rle", List.of("--block-type=1", "--content-size")),
                new Mode("compressed", List.of("--block-type=2")),
                new Mode("raw-literals", List.of("--block-type=2", "--literal-type=0")),
                new Mode("rle-literals", List.of("--block-type=2", "--literal-type=1")),
                new Mode("small-dictionary", List.of("--use-dict=1024")),
                new Mode("dictionary", List.of("--use-dict=32768")),
                new Mode("magicless", List.of("--no-magic")),
                new Mode("magicless-dictionary", List.of("--no-magic", "--use-dict=32768"))
        ).flatMap(mode -> Stream.of(1, 24301).map(seed -> Arguments.of(mode, seed)));
    }

    /// Exercises the generator's raw-block and header-only outputs, with and without dictionaries.
    private static Stream<Arguments> auxiliaryConfigurations() {
        return Stream.of(
                new Mode("blocks", List.of("--gen-blocks")),
                new Mode("dictionary-blocks", List.of("--gen-blocks", "--use-dict=32768")),
                new Mode("headers", List.of("--frame-header-only")),
                new Mode("dictionary-headers", List.of("--frame-header-only", "--use-dict=32768"))
        ).flatMap(mode -> Stream.of(1, 24301).map(seed -> Arguments.of(mode, seed)));
    }

    /// Keeps the producer and its source notices available even when native execution is disabled.
    @Test
    void retainsReferenceSources() throws IOException {
        Path root = Path.of(Objects.requireNonNull(System.getProperty("arkivo.zstd.referenceDirectory")));
        assertTrue(Files.readString(root.resolve("UPSTREAM.properties")).contains("version=1.5.7"));
        assertTrue(Files.readString(root.resolve("LICENSE")).contains("Redistribution and use"));
        String source = Files.readString(root.resolve("tests/decodecorpus.c"));
        assertTrue(source.contains("generateCorpusWithDict"));
        assertTrue(source.contains("outputBuffer(fr.srcStart"));
        assertTrue(Files.isRegularFile(root.resolve("tests/zstreamtest.c")));
        assertTrue(Files.isRegularFile(root.resolve("tests/invalidDictionaries.c")));
    }

    /// Wraps raw compressed blocks for the frame API and distinguishes complete headers from complete frames.
    @ParameterizedTest(name = "{0}, seed={1}")
    @MethodSource("auxiliaryConfigurations")
    void checksBlocksAndHeaders(Mode mode, int seed) throws IOException {
        String executable = executable();
        Path encodedDirectory = Files.createDirectory(directory.resolve("encoded"));
        Path plainDirectory = Files.createDirectory(directory.resolve("plain"));
        generate(executable, mode, seed, encodedDirectory, plainDirectory);
        assertEquals(FRAME_COUNT, fileCount(plainDirectory));
        boolean dictionaryMode = mode.options().contains("--use-dict=32768");
        assertEquals(FRAME_COUNT + (dictionaryMode ? 1 : 0), fileCount(encodedDirectory));
        byte @Nullable [] dictionaryBytes = dictionaryMode
                ? Files.readAllBytes(encodedDirectory.resolve("dictionary")) : null;
        @Nullable ZstdDictionary dictionary = dictionaryBytes == null ? null : ZstdDictionary.fullDictionary(dictionaryBytes);
        try (var nativeDecoder = new ZstdDecompressCtx(); var decoder = CODEC.newDecoder()) {
            if (dictionaryBytes != null) nativeDecoder.loadDict(dictionaryBytes);
            for (int index = 0; index < FRAME_COUNT; index++) {
                String name = String.format(java.util.Locale.ROOT, "z%06d", index);
                byte[] encoded = Files.readAllBytes(encodedDirectory.resolve(name + ".zst"));
                byte[] plain = Files.readAllBytes(plainDirectory.resolve(name));
                if (mode.options().contains("--frame-header-only")) {
                    ByteBuffer header = ByteBuffer.wrap(encoded).asReadOnlyBuffer();
                    assertEquals(encoded.length, CODEC.frameInfo(header).headerSize());
                    assertEquals(0, header.position());
                    assertEquals(0, plain.length);
                    assertThrows(IOException.class, () -> CODEC.frameCompressedSize(header));
                    ZstdCodec configured = dictionary == null ? CODEC : CODEC.withDictionary(dictionary);
                    try (var engine = configured.newDecoder()) {
                        assertThrows(IOException.class, () -> engine.finish(header, ByteBuffer.allocate(1)));
                    }
                } else {
                    byte[] frame = wrapBlock(encoded, plain.length, dictionary);
                    assertArrayEquals(plain, nativeDecoder.decompress(frame, plain.length));
                    inspect(CODEC, frame, plain.length, dictionary, true);
                    for (int shape = 0; shape < 3; shape++) {
                        decoder.reset();
                        assertArrayEquals(plain, decode(decoder, frame, dictionary, shape, plain.length));
                    }
                }
            }
        }
    }

    /// Adds a single-segment frame around one generated compressed block; no block bytes are changed.
    private static byte[] wrapBlock(byte @Unmodifiable [] block, int plainSize, @Nullable ZstdDictionary dictionary) {
        assertTrue(block.length <= 128 * 1024);
        int headerSize = dictionary == null ? 9 : 13;
        byte[] frame = new byte[headerSize + 3 + block.length];
        ByteArrayAccess.writeIntLittleEndian(frame, 0, 0xfd2fb528);
        frame[4] = (byte) (dictionary == null ? 0xa0 : 0xa3);
        if (dictionary != null) ByteArrayAccess.writeIntLittleEndian(frame, 5, (int) dictionary.dictionaryId());
        ByteArrayAccess.writeIntLittleEndian(frame, headerSize - 4, plainSize);
        // The temporary fourth byte is overwritten by the copied compressed block.
        ByteArrayAccess.writeIntLittleEndian(frame, headerSize, block.length << 3 | 5);
        System.arraycopy(block, 0, frame, headerSize + 3, block.length);
        return frame;
    }

    /// Checks full output, frame inspection, input lifetime, dictionary waits, resets, and malformed suffixes.
    @ParameterizedTest(name = "{0}, seed={1}")
    @MethodSource("configurations")
    void decodesGeneratedFrames(Mode mode, int seed) throws IOException {
        String executable = executable();
        Path encodedDirectory = Files.createDirectory(directory.resolve("encoded"));
        Path plainDirectory = Files.createDirectory(directory.resolve("plain"));
        generate(executable, mode, seed, encodedDirectory, plainDirectory);
        assertEquals(FRAME_COUNT, fileCount(plainDirectory));
        boolean dictionaryMode = mode.options().stream().anyMatch(option -> option.startsWith("--use-dict="));
        assertEquals(FRAME_COUNT + (dictionaryMode ? 1 : 0), fileCount(encodedDirectory));
        byte @Nullable [] dictionaryBytes = dictionaryMode
                ? Files.readAllBytes(encodedDirectory.resolve("dictionary")) : null;
        @Nullable ZstdDictionary dictionary = dictionaryBytes == null ? null : ZstdDictionary.fullDictionary(dictionaryBytes);
        ZstdFrameFormat format = mode.options().contains("--no-magic")
                ? ZstdFrameFormat.MAGICLESS : ZstdFrameFormat.STANDARD;
        ZstdCodec codec = CODEC.withFrameFormat(format);
        var concatenated = new ByteArrayOutputStream();
        var concatenatedPlain = new ByteArrayOutputStream();
        boolean huffmanLiterals = false;
        try (var nativeDecoder = new ZstdDecompressCtx(); var decoder = codec.newDecoder()) {
            if (dictionaryBytes != null) nativeDecoder.loadDict(dictionaryBytes);
            for (int index = 0; index < FRAME_COUNT; index++) {
                String name = String.format(java.util.Locale.ROOT, "z%06d", index);
                byte[] encoded = Files.readAllBytes(encodedDirectory.resolve(name + ".zst"));
                byte[] plain = Files.readAllBytes(plainDirectory.resolve(name));
                String context = mode + ", seed=" + seed + ", frame=" + index;
                assertTrue(plain.length <= 1 << 20, context);
                assertArrayEquals(plain, nativeDecoder.decompress(standardFrame(encoded, format), plain.length), context);
                inspect(codec, encoded, plain.length, dictionary, mode.options().contains("--content-size"));
                for (int shape = 0; shape < 3; shape++) {
                    decoder.reset();
                    assertArrayEquals(plain, decode(decoder, encoded, dictionary, shape, plain.length), context);
                }
                ZstdCodec configured = dictionary == null ? codec : codec.withDictionary(dictionary);
                try (var input = configured.newInputStream(new ByteArrayInputStream(encoded))) {
                    assertArrayEquals(plain, input.readAllBytes(), context);
                }
                // A small, deterministic prefix set exercises truncation without quadratic work on megabyte frames.
                for (int length : new int[]{1, encoded.length / 2, encoded.length - 1}) {
                    byte[] truncated = Arrays.copyOf(encoded, length);
                    try (var input = configured.newInputStream(new ByteArrayInputStream(truncated))) {
                        assertThrows(IOException.class, input::readAllBytes, context + ", prefix=" + length);
                    }
                }
                ZstdStandardFrameInfo info = assertInstanceOf(ZstdStandardFrameInfo.class,
                        codec.frameInfo(ByteBuffer.wrap(encoded)));
                huffmanLiterals |= hasHuffmanLiterals(encoded, info.headerSize());
                if (info.checksum()) {
                    byte[] damaged = encoded.clone();
                    damaged[damaged.length - 1] ^= 1;
                    try (var input = configured.newInputStream(new ByteArrayInputStream(damaged))) {
                        assertThrows(IOException.class, input::readAllBytes, context + ", checksum");
                    }
                }
                concatenated.writeBytes(encoded);
                concatenatedPlain.writeBytes(plain);
            }
        }
        // Forcing literal-type=2 in 1.5.7 can crash the generator on blocks shorter than 64 bytes.
        // Check that automatic selection actually exercises Huffman literals rather than losing that coverage.
        if (mode.name().equals("compressed")) assertTrue(huffmanLiterals, "no Huffman literals generated");
        ZstdCodec combinedCodec = codec.withMaximumOutputSize(concatenatedPlain.size());
        if (dictionary != null) combinedCodec = combinedCodec.withDictionary(dictionary);
        try (var input = combinedCodec.newInputStream(new ByteArrayInputStream(concatenated.toByteArray()))) {
            assertArrayEquals(concatenatedPlain.toByteArray(), input.readAllBytes());
        }
    }

    /// Inspects physical block and literal tags without interpreting compressed Huffman data.
    private static boolean hasHuffmanLiterals(byte @Unmodifiable [] encoded, int offset) {
        while (true) {
            int header = ByteArrayAccess.readIntLittleEndian(encoded, offset) & 0xffffff;
            offset += 3;
            int type = (header >>> 1) & 3;
            int size = header >>> 3;
            if (type == 2 && size > 0 && (encoded[offset] & 3) >= 2) return true;
            offset += type == 1 ? 1 : size;
            if ((header & 1) != 0) return false;
        }
    }

    /// Checks read-only header inspection against the producer's plaintext and optional full dictionary.
    private static void inspect(ZstdCodec codec, byte @Unmodifiable [] encoded, int plainSize,
                                @Nullable ZstdDictionary dictionary, boolean knownSize) throws IOException {
        ByteBuffer source = ByteBuffer.allocate(encoded.length + 2);
        source.position(1).put(encoded).flip().position(1);
        ByteBuffer view = source.asReadOnlyBuffer();
        ZstdStandardFrameInfo info = assertInstanceOf(ZstdStandardFrameInfo.class, codec.frameInfo(view));
        assertEquals(1, view.position());
        assertEquals(encoded.length + 1, view.limit());
        assertEquals(encoded.length, codec.frameCompressedSize(view));
        assertEquals(1, view.position());
        if (knownSize || info.contentSize() != CompressionCodec.UNKNOWN_SIZE) {
            assertEquals(plainSize, info.contentSize());
        }
        if (info.dictionaryId() > 0) {
            assertNotNull(dictionary);
            assertEquals(dictionary.dictionaryId(), info.dictionaryId());
        }
    }

    /// Supplies fresh chunks and poisons consumed input so retained caller storage cannot silently work.
    private static byte[] decode(CompressionDecoder.FramedDictionaryAware<ZstdDictionary, ZstdDictionaryRequest> decoder,
                                 byte @Unmodifiable [] encoded,
                                 @Nullable ZstdDictionary dictionary, int shape, int maximumOutput) throws IOException {
        int chunk = shape == 0 ? encoded.length + 3 : shape == 1 ? 1019 : 7;
        int supplied = 0;
        byte[] all = Arrays.copyOf(encoded, encoded.length + 3);
        all[encoded.length] = 0x12;
        all[encoded.length + 1] = 0x34;
        all[encoded.length + 2] = 0x56;
        ByteBuffer storage = ByteBuffer.allocate(0);
        ByteBuffer source = storage;
        ByteBuffer target = shape == 1 ? ByteBuffer.allocateDirect(4095) : ByteBuffer.allocate(4095);
        var result = new ByteArrayOutputStream();
        for (int iteration = 0; iteration < encoded.length * 2L + maximumOutput + 100; iteration++) {
            if (!source.hasRemaining() && supplied < all.length) {
                int count = Math.min(chunk, all.length - supplied);
                storage = shape == 1 ? ByteBuffer.allocateDirect(count + 2) : ByteBuffer.allocate(count + 2);
                storage.put((byte) 0x55).put(all, supplied, count).put((byte) 0x66).flip();
                storage.position(1).limit(count + 1);
                source = shape == 2 ? storage.asReadOnlyBuffer() : storage;
                supplied += count;
            }
            int before = source.position();
            target.clear().put((byte) 0x33);
            target.put(target.capacity() - 1, (byte) 0x44);
            target.limit(iteration % 11 == 0 ? 1 : target.capacity() - 1);
            CodecOutcome outcome = decoder.decode(source, target);
            int produced = target.position() - 1;
            for (int offset = 1; offset <= produced; offset++) result.write(target.get(offset));
            assertTrue(result.size() <= maximumOutput);
            target.limit(target.capacity());
            assertEquals((byte) 0x33, target.get(0));
            assertEquals((byte) 0x44, target.get(target.capacity() - 1));
            for (int offset = before; offset < source.position(); offset++) storage.put(offset, (byte) 0xa5);
            if (outcome == CodecOutcome.FINISHED) {
                assertEquals(encoded.length, supplied - source.remaining());
                var tail = new ByteArrayOutputStream();
                while (source.hasRemaining()) tail.write(source.get());
                tail.write(all, supplied, all.length - supplied);
                assertArrayEquals(new byte[]{0x12, 0x34, 0x56}, tail.toByteArray());
                return result.toByteArray();
            }
            if (outcome == CodecOutcome.NEEDS_DICTIONARY) {
                assertNotNull(dictionary);
                assertEquals(dictionary.dictionaryId(), decoder.dictionaryRequest().dictionaryId());
                int position = source.position();
                target.clear();
                assertEquals(CodecOutcome.NEEDS_DICTIONARY, decoder.decode(source, target));
                assertEquals(position, source.position());
                assertEquals(0, target.position());
                decoder.provideDictionary(dictionary);
            } else if (outcome == CodecOutcome.NEEDS_INPUT) {
                assertFalse(source.hasRemaining());
                assertTrue(supplied < all.length, "unexpected read past frame suffix");
            } else {
                assertEquals(CodecOutcome.NEEDS_OUTPUT, outcome);
            }
        }
        throw new AssertionError("Decoder did not finish within the bounded call count");
    }

    /// Adds only the standard magic for the native decoder when the generator omitted it.
    private static byte[] standardFrame(byte @Unmodifiable [] encoded, ZstdFrameFormat format) {
        if (format == ZstdFrameFormat.STANDARD) return encoded.clone();
        var result = new ByteArrayOutputStream();
        result.writeBytes(new byte[]{0x28, (byte) 0xb5, 0x2f, (byte) 0xfd});
        result.writeBytes(encoded);
        return result.toByteArray();
    }

    /// Runs one bounded generator invocation with explicit seed, output paths, and size limits.
    private void generate(String executable, Mode mode, int seed, Path encoded, Path plain) throws IOException {
        List<String> command = new ArrayList<>(List.of(executable, "-s" + seed, "-n" + FRAME_COUNT,
                "-p" + encoded, "-o" + plain, "--max-content-size-log=15"));
        command.addAll(mode.options());
        Path log = directory.resolve("decodecorpus.log");
        Process process = new ProcessBuilder(command).directory(directory.toFile()).redirectErrorStream(true)
                .redirectOutput(log.toFile()).start();
        try {
            assertTrue(process.waitFor(60, TimeUnit.SECONDS), () -> "Generator timed out: " + command);
            assertEquals(0, process.exitValue(), () -> "Generator failed: " + command + ": " + diagnostics(log));
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            throw new IOException("Interrupted while generating Zstandard frames", exception);
        } finally {
            if (process.isAlive()) process.destroyForcibly();
        }
    }

    /// Reads native diagnostics for a failed test without replacing the original assertion.
    private static String diagnostics(Path log) {
        try {
            return Files.readString(log);
        } catch (IOException exception) {
            return exception.toString();
        }
    }

    /// Counts generated files, detecting missing or extra outputs before decoding.
    private static long fileCount(Path directory) throws IOException {
        try (var files = Files.list(directory)) {
            return files.filter(Files::isRegularFile).count();
        }
    }

    /// Resolves explicit native-tool configuration without searching the ambient executable path.
    private static String executable() {
        @Nullable String value = System.getenv("ARKIVO_ZSTD_DECODECORPUS_EXECUTABLE");
        if (value == null || value.isBlank()) {
            if (Boolean.parseBoolean(System.getenv("ARKIVO_REQUIRE_ZSTD_DECODECORPUS"))) {
                fail("Set ARKIVO_ZSTD_DECODECORPUS_EXECUTABLE to the Zstandard 1.5.7 decodecorpus executable");
            }
            assumeTrue(false, "Zstandard decodecorpus is not configured");
            throw new AssertionError();
        }
        Path path = Path.of(value).toAbsolutePath();
        assertTrue(Files.isRegularFile(path), "Missing decodecorpus executable: " + path);
        return path.toString();
    }

    /// Selects generator options without storing mutable shared process state.
    ///
    /// @param name the diagnostic profile name
    /// @param options the immutable generator arguments
    @NotNullByDefault
    private record Mode(String name, @Unmodifiable List<String> options) {
        /// Returns the concise name in parameterized test reports.
        @Override
        public String toString() {
            return name;
        }
    }
}
