// Copyright (c) 2026 Glavo
// Scenarios and fixture passwords adapted from Zip4j's integration tests; see LICENSES/Apache-2.0.txt.
// SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

package org.glavo.arkivo.all;

import net.lingala.zip4j.ZipFile;
import net.lingala.zip4j.io.outputstream.ZipOutputStream;
import net.lingala.zip4j.model.ZipParameters;
import net.lingala.zip4j.model.enums.AesKeyStrength;
import net.lingala.zip4j.model.enums.AesVersion;
import net.lingala.zip4j.model.enums.CompressionMethod;
import net.lingala.zip4j.model.enums.EncryptionMethod;
import org.glavo.arkivo.all.commonscompress.ArchiveCorpusAssertions;
import org.glavo.arkivo.archive.ArchiveMetadataDecoder;
import org.glavo.arkivo.archive.ArkivoPasswordProvider;
import org.glavo.arkivo.archive.zip.ZipArchiveOptions;
import org.glavo.arkivo.archive.zip.ZipArkivoEntryAttributeView;
import org.glavo.arkivo.archive.zip.ZipArkivoFileSystem;
import org.glavo.arkivo.archive.zip.ZipArkivoStreamingReader;
import org.glavo.arkivo.archive.zip.ZipArkivoStreamingWriter;
import org.glavo.arkivo.archive.zip.ZipEncryption;
import org.jetbrains.annotations.NotNullByDefault;
import org.jetbrains.annotations.Nullable;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.EnumSource;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.ValueSource;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/// Checks Zip4j regression archives and bidirectional encryption interoperability without extracting to host paths.
@NotNullByDefault
final class Zip4jInteropTest {
    /// The non-secret password used by the upstream generated archives.
    private static final String PASSWORD = "test123!";

    /// Compares complete bodies from ordinary historical archives against Zip4j's decoder.
    @ParameterizedTest
    @ValueSource(strings = {"archive-with-no-dir-entries.zip", "cen_dir_entries_diff_order_as_local_entries.zip",
            "remove_file_with_similar_file_names.zip", "valid_empty_zip_file.zip",
            "dirs_with_extended_local_file_headers.zip", "content_in_entry_which_is_directory.jar",
            "jar-dir-fh-entry-size-2.jar", "jar-dir-lfh-and-fh-entry-size-2.jar", "corrupt_extra_data_record_length.zip",
            "archive_with_invalid_zip64_headers.zip"})
    void readsRegressionArchives(String name) throws IOException {
        assertReadable(archive(name), StandardCharsets.UTF_8, Map.of(), false);
    }

    /// Reads the stored AES archive generated by Zip4j 1.3.3 with its distinct upstream password.
    @Test
    void readsLegacyStoredAes() throws IOException {
        assertReadable(archive("store_compression_made_with_v1.3.3.zip"), StandardCharsets.UTF_8,
                Map.of("*", "aaaaaaaa"), false);
    }

    /// Keeps Arkivo's exact end-record boundary requirement even where Zip4j tolerates trailing bytes.
    @Test
    void rejectsTrailingBytesAfterEndRecord() throws IOException {
        Path archive = archive("end_of_cen_dir_not_at_expected_position.zip");
        try (var reference = new ZipFile(archive.toFile())) {
            assertEquals(19, reference.getFileHeaders().size());
            for (var header : reference.getFileHeaders()) {
                if (!header.isDirectory()) {
                    try (var input = reference.getInputStream(header)) {
                        assertEquals(header.getUncompressedSize(), input.transferTo(java.io.OutputStream.nullOutputStream()));
                    }
                }
            }
        }
        IOException failure = assertThrows(IOException.class, () -> {
            try (var fileSystem = ZipArkivoFileSystem.open(archive)) {
                ArchiveCorpusAssertions.readFileSystem(fileSystem);
            }
        });
        assertEquals("ZIP end of central directory record not found", failure.getMessage());
    }

    /// Resolves a ZIP64 field containing sizes but no offset, using the upstream fixture's password.
    @Test
    void readsSizeOnlyZip64() throws IOException {
        assertReadable(archive("zip64_with_only_file_sizes.zip"), StandardCharsets.UTF_8,
                Map.of("*", "Shu1an@2019GTS"), false);
    }

    /// Uses the same explicit GBK fallback as the upstream 7-Zip filename regression.
    @Test
    void readsGbkNames() throws IOException {
        assertReadable(archive("testfile_with_chinese_filename_by_7zip.zip"), Charset.forName("GBK"), Map.of(), false);
    }

    /// Reads an encrypted archive with an opaque malformed extra-field tail using its upstream password.
    @Test
    void readsOpaqueExtraFieldTail() throws IOException {
        assertReadable(archive("invalid_extra_data_record.zip"), StandardCharsets.UTF_8,
                Map.of("*", "password"), false);
    }

    /// Resolves archive-local links without creating host symlinks and retains their raw streaming bodies.
    @Test
    void readsSymbolicLinks() throws IOException {
        Path archive = archive("zipWithLinkToDirAndFolder.zip");
        Map<String, String> targets = Map.of("b", "a", "d", "c");
        try (var reference = new ZipFile(archive.toFile());
             var fileSystem = ZipArkivoFileSystem.open(archive)) {
            assertEquals(5, reference.getFileHeaders().size());
            for (var link : targets.entrySet()) {
                try (var input = reference.getInputStream(reference.getFileHeader(link.getKey()))) {
                    assertArrayEquals(link.getValue().getBytes(StandardCharsets.UTF_8), input.readAllBytes());
                }
                Path path = fileSystem.getPath("/" + link.getKey());
                assertTrue(Files.isSymbolicLink(path));
                assertEquals(link.getValue(), Files.readSymbolicLink(path).toString());
            }
            assertTrue(Files.isDirectory(fileSystem.getPath("/b")));
            assertTrue(Files.isRegularFile(fileSystem.getPath("/d")));
            assertArrayEquals(new byte[0], Files.readAllBytes(fileSystem.getPath("/d")));
        }
        try (var reader = ZipArkivoStreamingReader.open(archive)) {
            int entries = 0;
            var links = new HashSet<String>();
            while (reader.next()) {
                entries++;
                String name = reader.readAttributes().path();
                if (targets.containsKey(name)) {
                    links.add(name);
                    // Unix file types live in the central directory, not in these local headers.
                    assertFalse(reader.readAttributes().isSymbolicLink());
                    try (var input = reader.openInputStream()) {
                        assertArrayEquals(targets.get(name).getBytes(StandardCharsets.UTF_8), input.readAllBytes());
                    }
                }
            }
            assertEquals(5, entries);
            assertEquals(targets.keySet(), links);
        }
    }

    /// Rejects unsupported PKWARE strong encryption instead of interpreting it as traditional ZipCrypto.
    @Test
    void rejectsStrongEncryption() {
        var options = readOptions(StandardCharsets.UTF_8, Map.of("*", PASSWORD));
        IOException indexedFailure = assertThrows(IOException.class, () -> {
            try (var fileSystem = ZipArkivoFileSystem.open(archive("strong_encrypted.zip"), options)) {
                Files.readAllBytes(fileSystem.getPath("/test.txt"));
            }
        });
        assertTrue(indexedFailure.getMessage().startsWith("Unsupported ZIP encryption method"));
        IOException streamingFailure = assertThrows(IOException.class, () -> {
            try (var reader = ZipArkivoStreamingReader.open(archive("strong_encrypted.zip"), options)) {
                assertTrue(reader.next());
                try (var input = reader.openInputStream()) {
                    input.readAllBytes();
                }
            }
        });
        assertTrue(streamingFailure.getMessage().startsWith("Unsupported ZIP encryption method"));
    }

    /// Rejects broken end records and duplicate indexed paths rather than repairing them implicitly.
    @ParameterizedTest
    @ValueSource(strings = {"invalid_zip_file_size_less_than_22kb.zip", "zip_with_corrupt_comment_length.zip",
            "zip_with_duplicate_entries.zip"})
    void rejectsBrokenIndex(String name) {
        assertThrows(IOException.class, () -> {
            try (var fileSystem = ZipArkivoFileSystem.open(archive(name))) {
                ArchiveCorpusAssertions.readFileSystem(fileSystem);
            }
        });
    }

    /// Selects each encrypted entry's password independently and compares bodies with the original resource files.
    @Test
    void readsDifferentPasswordsWithoutLeakingEntryState() throws IOException {
        Map<String, String> passwords = Map.of("after_deflate_remaining_bytes.bin", "password_1",
                "file_PDF_1MB.pdf", "password_2");
        Path archive = archive("zip_with_different_passwords.zip");
        assertReadable(archive, StandardCharsets.UTF_8, passwords, false);
        try (var fileSystem = ZipArkivoFileSystem.open(archive, readOptions(StandardCharsets.UTF_8, passwords))) {
            for (String name : List.of("after_deflate_remaining_bytes.bin", "file_PDF_1MB.pdf")) {
                assertArrayEquals(Files.readAllBytes(content(name)), Files.readAllBytes(fileSystem.getPath("/" + name)));
            }
            // This archive contains an older sample.pdf, not the current test-files/sample.pdf resource.
            assertEquals(3028, Files.size(fileSystem.getPath("/sample.pdf")));
        }
    }

    /// Rejects independently supplied authentication, checksum, and truncated-header failures through both APIs.
    @ParameterizedTest
    @ValueSource(strings = {"aes_with_extra_data_record_and_corrupt_mac.zip", "entry_with_checksum_mismatch.zip",
            "invalid_aes_extra_data_record_length_in_header", "null-aes-key-strength-in-aes-extra-data-record",
            "file_name_size_is_0_in_local_file_header", "unexpected-eof-when-reading-stream",
            "missing_exended_local_file_header.zip"})
    void rejectsCorruptRecords(String name) {
        var options = readOptions(StandardCharsets.UTF_8, Map.of("*", PASSWORD));
        assertThrows(IOException.class, () -> {
            try (var fileSystem = ZipArkivoFileSystem.open(archive(name), options)) {
                ArchiveCorpusAssertions.readFileSystem(fileSystem);
            }
        });
        assertThrows(IOException.class, () -> {
            try (var reader = ZipArkivoStreamingReader.open(archive(name), options)) {
                while (reader.next()) {
                    try (var input = reader.openInputStream()) {
                        input.transferTo(java.io.OutputStream.nullOutputStream());
                    }
                }
            }
        });
    }

    /// Covers both ZIP methods and single-volume versus split output with the encryption modes Zip4j can encode.
    private static Stream<Arguments> generatedConfigurations() {
        return Stream.of(CompressionMethod.STORE, CompressionMethod.DEFLATE).flatMap(method ->
                // Zip4j 2.11.5 decodes AES-192 but explicitly rejects encoding it; the reverse test covers decoding.
                Stream.of(ZipEncryption.values()).filter(encryption -> encryption != ZipEncryption.WINZIP_AES_192).flatMap(encryption ->
                        Stream.of(false, true).map(split -> Arguments.of(method, encryption, split))));
    }

    /// Reads Zip4j-generated split and ordinary archives and validates each body against its source file.
    @ParameterizedTest
    @MethodSource("generatedConfigurations")
    void readsGeneratedArchives(CompressionMethod method, ZipEncryption encryption, boolean split,
                               @TempDir Path directory) throws IOException {
        Path archive = directory.resolve("generated.zip");
        var parameters = new ZipParameters();
        parameters.setCompressionMethod(method);
        parameters.setEncryptFiles(encryption != ZipEncryption.NONE);
        parameters.setEncryptionMethod(encryption == ZipEncryption.NONE ? EncryptionMethod.NONE
                : encryption == ZipEncryption.ZIP_CRYPTO ? EncryptionMethod.ZIP_STANDARD : EncryptionMethod.AES);
        parameters.setAesKeyStrength(switch (encryption) {
            case WINZIP_AES_128 -> AesKeyStrength.KEY_STRENGTH_128;
            case WINZIP_AES_192 -> AesKeyStrength.KEY_STRENGTH_192;
            default -> AesKeyStrength.KEY_STRENGTH_256;
        });
        var names = List.of("file_PDF_1MB.pdf", "sample_text1.txt", "zero_byte_file.txt");
        try (var reference = new ZipFile(archive.toFile(), PASSWORD.toCharArray())) {
            reference.createSplitZipFile(names.stream().map(name -> content(name).toFile()).toList(),
                    parameters, split, split ? 65536 : -1);
        }
        if (split) {
            assertTrue(Files.isRegularFile(directory.resolve("generated.z01")));
        }
        Map<String, String> passwords = Map.of("*", PASSWORD);
        assertReadable(archive, StandardCharsets.UTF_8, passwords, split);
        try (var fileSystem = ZipArkivoFileSystem.open(archive, readOptions(StandardCharsets.UTF_8, passwords))) {
            for (String name : names) {
                assertArrayEquals(Files.readAllBytes(content(name)), Files.readAllBytes(fileSystem.getPath("/" + name)));
            }
        }
    }

    /// Combines AES versions with stored/deflated bodies and known-size/descriptor entry boundaries.
    private static Stream<Arguments> aesConfigurations() {
        return Stream.of(CompressionMethod.STORE, CompressionMethod.DEFLATE).flatMap(method ->
                Stream.of(AesVersion.ONE, AesVersion.TWO).flatMap(version ->
                        Stream.of(false, true).map(descriptor -> Arguments.of(method, version, descriptor))));
    }

    /// Checks independently generated AE-1 and AE-2 entries, including empty entries and following records.
    @ParameterizedTest
    @MethodSource("aesConfigurations")
    void readsAesVersions(CompressionMethod method, AesVersion version, boolean descriptor,
                         @TempDir Path directory) throws IOException {
        Path archive = directory.resolve("aes.zip");
        writeAesArchive(archive, method, version, descriptor);
        assertReadable(archive, StandardCharsets.UTF_8, Map.of("*", PASSWORD), false);
    }

    /// Checks entry alignment after skipping unopened bodies or closing bodies read only in part.
    @ParameterizedTest
    @MethodSource("aesConfigurations")
    void partiallyReadsAesEntries(CompressionMethod method, AesVersion version, boolean descriptor,
                                 @TempDir Path directory) throws IOException {
        Path archive = directory.resolve("partial.zip");
        writeAesArchive(archive, method, version, descriptor);
        var options = readOptions(StandardCharsets.UTF_8, Map.of("*", PASSWORD));
        for (int prefix : new int[]{0, 1, 17}) {
            try (var reader = ZipArkivoStreamingReader.open(archive, options)) {
                assertTrue(reader.next());
                assertEquals("sample_text1.txt", reader.readAttributes().path());
                if (prefix != 0) {
                    var input = reader.openInputStream();
                    assertArrayEquals(java.util.Arrays.copyOf(Files.readAllBytes(content("sample_text1.txt")), prefix),
                            input.readNBytes(prefix));
                    if (prefix == 1) {
                        input.close();
                        input.close();
                    }
                    // For the other prefix, next() closes the still-open body itself.
                    assertTrue(reader.next());
                    assertThrows(IOException.class, input::read);
                } else {
                    assertTrue(reader.next());
                }
                assertEquals("zero_byte_file.txt", reader.readAttributes().path());
                try (var input = reader.openInputStream()) {
                    assertEquals(-1, input.read());
                }
                assertTrue(reader.next());
                assertEquals("sample.pdf", reader.readAttributes().path());
                try (var input = reader.openInputStream()) {
                    assertArrayEquals(Files.readAllBytes(content("sample.pdf")), input.readAllBytes());
                }
                assertFalse(reader.next());
            }
        }
    }

    /// Checks that entry close, cursor advance, and reader close all authenticate an opened partial AES body.
    @ParameterizedTest
    @MethodSource("aesConfigurations")
    void rejectsCorruptAesOnDrain(CompressionMethod method, AesVersion version, boolean descriptor,
                                 @TempDir Path directory) throws IOException {
        Path archive = directory.resolve("authentication.zip");
        writeAesArchive(archive, method, version, descriptor);
        corruptFirstAesAuthentication(archive);
        try (var reference = new ZipFile(archive.toFile(), PASSWORD.toCharArray())) {
            assertThrows(IOException.class, () -> {
                try (var input = reference.getInputStream(reference.getFileHeaders().get(0))) {
                    input.readAllBytes();
                }
            });
        }
        var options = readOptions(StandardCharsets.UTF_8, Map.of("*", PASSWORD));
        for (int operation = 0; operation < 3; operation++) {
            try (var reader = ZipArkivoStreamingReader.open(archive, options)) {
                assertTrue(reader.next());
                var input = reader.openInputStream();
                assertEquals(Byte.toUnsignedInt(Files.readAllBytes(content("sample_text1.txt"))[0]), input.read());
                switch (operation) {
                    case 0 -> assertThrows(IOException.class, input::close);
                    case 1 -> assertThrows(IOException.class, reader::next);
                    case 2 -> assertThrows(IOException.class, reader::close);
                    default -> throw new AssertionError(operation);
                }
                assertThrows(IOException.class, input::read);
                input.close();
            }
        }
    }

    /// Changes only the first entry's trailing authentication code, leaving ciphertext and ZIP metadata intact.
    private static void corruptFirstAesAuthentication(Path archive) throws IOException {
        long compressedSize;
        try (var reference = new ZipFile(archive.toFile(), PASSWORD.toCharArray())) {
            compressedSize = reference.getFileHeaders().get(0).getCompressedSize();
        }
        byte[] bytes = Files.readAllBytes(archive);
        var buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);
        int data = 30 + Short.toUnsignedInt(buffer.getShort(26)) + Short.toUnsignedInt(buffer.getShort(28));
        bytes[Math.toIntExact(data + compressedSize - 1)] ^= 1;
        Files.write(archive, bytes);
    }

    /// Returns AES combinations whose local headers declare sizes without data descriptors.
    private static Stream<Arguments> knownSizeAesConfigurations() {
        return aesConfigurations().filter(arguments -> !(boolean) arguments.get()[2]);
    }

    /// Distinguishes raw skipping from validated reads without requesting passwords for skipped entries.
    @ParameterizedTest
    @MethodSource("knownSizeAesConfigurations")
    void skipsUnopenedKnownSizeAes(CompressionMethod method, AesVersion version, boolean descriptor,
                                   @TempDir Path directory) throws IOException {
        Path archive = directory.resolve("skip.zip");
        writeAesArchive(archive, method, version, descriptor);
        corruptFirstAesAuthentication(archive);
        var requests = new java.util.concurrent.atomic.AtomicInteger();
        var options = ZipArchiveOptions.READ_DEFAULTS.withPasswordProvider(request -> {
            assertEquals("/sample.pdf", request.entryPath());
            requests.incrementAndGet();
            return PASSWORD.getBytes(StandardCharsets.UTF_8);
        });
        try (var reader = ZipArkivoStreamingReader.open(archive, options)) {
            assertTrue(reader.next());
            assertEquals("sample_text1.txt", reader.readAttributes().path());
            assertTrue(reader.next());
            assertEquals("zero_byte_file.txt", reader.readAttributes().path());
            assertTrue(reader.next());
            assertEquals(0, requests.get());
            assertEquals("sample.pdf", reader.readAttributes().path());
            try (var input = reader.openInputStream()) {
                assertArrayEquals(Files.readAllBytes(content("sample.pdf")), input.readAllBytes());
            }
            assertEquals(1, requests.get());
            assertFalse(reader.next());
        }
    }

    /// Rejects an incorrect AE-1 body CRC or nonzero AE-2 descriptor CRC with intact ciphertext authentication.
    @ParameterizedTest
    @MethodSource("aesCrcConfigurations")
    void rejectsAesCrcMismatch(CompressionMethod method, AesVersion version, boolean descriptor,
                               @TempDir Path directory) throws IOException {
        Path archive = directory.resolve("crc.zip");
        writeAesArchive(archive, method, version, descriptor);
        long compressedSize;
        long crc;
        try (var reference = new ZipFile(archive.toFile(), PASSWORD.toCharArray())) {
            var header = reference.getFileHeaders().get(0);
            compressedSize = header.getCompressedSize();
            crc = header.getCrc();
        }
        byte[] bytes = Files.readAllBytes(archive);
        var buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);
        int changedCrc = (int) crc ^ 1;
        int central = buffer.getInt(bytes.length - 22 + 16);
        assertEquals(0x02014b50, buffer.getInt(central));
        buffer.putInt(central + 16, changedCrc);
        if (descriptor) {
            int data = 30 + Short.toUnsignedInt(buffer.getShort(26)) + Short.toUnsignedInt(buffer.getShort(28));
            int record = Math.toIntExact(data + compressedSize);
            assertEquals(0x08074b50, buffer.getInt(record));
            buffer.putInt(record + 4, changedCrc);
        } else {
            buffer.putInt(14, changedCrc);
        }
        Files.write(archive, bytes);
        var options = readOptions(StandardCharsets.UTF_8, Map.of("*", PASSWORD));
        // AE-2 deliberately omits plaintext CRC validation; its descriptor still has a required zero CRC.
        if (version == AesVersion.ONE) {
            assertThrows(IOException.class, () -> {
                try (var fileSystem = ZipArkivoFileSystem.open(archive, options)) {
                    Files.readAllBytes(fileSystem.getPath("/sample_text1.txt"));
                }
            });
        }
        try (var reader = ZipArkivoStreamingReader.open(archive, options)) {
            assertTrue(reader.next());
            IOException failure = assertThrows(IOException.class, () -> {
                try (var input = reader.openInputStream()) {
                    input.readAllBytes();
                }
            });
            assertTrue(failure.getMessage().contains(descriptor ? "data descriptor" : "local header"), failure.getMessage());
        }
    }

    /// Covers AE-1 body checks and the required zero CRC in AE-2 descriptors.
    private static Stream<Arguments> aesCrcConfigurations() {
        return aesConfigurations().filter(arguments -> arguments.get()[1] == AesVersion.ONE
                || (boolean) arguments.get()[2]);
    }

    /// Writes AES entries with Zip4j and checks that it emitted the requested version and boundary representation.
    private static void writeAesArchive(Path archive, CompressionMethod method, AesVersion version, boolean descriptor)
            throws IOException {
        var parameters = new ZipParameters();
        parameters.setCompressionMethod(method);
        parameters.setEncryptFiles(true);
        parameters.setEncryptionMethod(EncryptionMethod.AES);
        parameters.setAesKeyStrength(AesKeyStrength.KEY_STRENGTH_256);
        parameters.setAesVersion(version);
        var names = List.of("sample_text1.txt", "zero_byte_file.txt", "sample.pdf");
        if (descriptor) {
            try (var output = new ZipOutputStream(Files.newOutputStream(archive), PASSWORD.toCharArray())) {
                for (String name : names) {
                    parameters.setFileNameInZip(name);
                    parameters.setEntrySize(Files.size(content(name)));
                    output.putNextEntry(parameters);
                    Files.copy(content(name), output);
                    output.closeEntry();
                }
            }
        } else {
            try (var reference = new ZipFile(archive.toFile(), PASSWORD.toCharArray())) {
                reference.addFiles(names.stream().map(name -> content(name).toFile()).toList(), parameters);
            }
        }
        try (var reference = new ZipFile(archive.toFile(), PASSWORD.toCharArray())) {
            for (var header : reference.getFileHeaders()) {
                assertEquals(version, header.getAesExtraDataRecord().getAesVersion());
                assertEquals(descriptor, header.isDataDescriptorExists());
                try (var input = reference.getInputStream(header)) {
                    assertArrayEquals(Files.readAllBytes(content(header.getFileName())), input.readAllBytes());
                }
            }
        }
    }

    /// Lets Zip4j independently authenticate and decode Arkivo's AES, ZipCrypto, and unencrypted output.
    @ParameterizedTest
    @EnumSource(ZipEncryption.class)
    void zip4jReadsArkivoOutput(ZipEncryption encryption, @TempDir Path directory) throws IOException {
        Path archive = directory.resolve("arkivo.zip");
        var options = ZipArchiveOptions.CREATE_DEFAULTS.withPasswordProvider(
                ArkivoPasswordProvider.fixed(PASSWORD.getBytes(StandardCharsets.UTF_8)));
        var names = List.of("sample_text1.txt", "sample.pdf", "zero_byte_file.txt");
        try (var writer = ZipArkivoStreamingWriter.create(archive, options)) {
            for (String name : names) {
                try (var entry = writer.beginFile(name)) {
                    Objects.requireNonNull(entry.attributeView(ZipArkivoEntryAttributeView.class)).setEncryption(encryption);
                    try (var output = entry.openOutputStream()) {
                        Files.copy(content(name), output);
                    }
                }
            }
        }
        try (var reference = new ZipFile(archive.toFile(), PASSWORD.toCharArray())) {
            assertEquals(names.size(), reference.getFileHeaders().size());
            for (String name : names) {
                try (var input = reference.getInputStream(reference.getFileHeader(name))) {
                    assertArrayEquals(Files.readAllBytes(content(name)), input.readAllBytes());
                }
            }
        }
    }

    /// Compares physical entry names and full bodies, permitting NIO's additional implicit directories.
    private static void assertReadable(Path archive, Charset charset, Map<String, String> passwords, boolean split)
            throws IOException {
        Map<String, byte[]> expected = new HashMap<>();
        var directories = new HashSet<String>();
        try (var reference = new ZipFile(archive.toFile())) {
            reference.setCharset(charset);
            for (var header : reference.getFileHeaders()) {
                String name = header.getFileName().replace('\\', '/');
                if (header.isDirectory()) {
                    directories.add(name);
                } else {
                    reference.setPassword(passwords.getOrDefault(name, passwords.getOrDefault("*", "")).toCharArray());
                    try (var input = reference.getInputStream(header)) {
                        assertNull(expected.put(name, input.readAllBytes()), "Duplicate reference path: " + name);
                    }
                }
            }
        }
        var options = readOptions(charset, passwords);
        try (var fileSystem = ZipArkivoFileSystem.open(archive, options)) {
            for (var entry : expected.entrySet()) {
                assertArrayEquals(entry.getValue(), Files.readAllBytes(fileSystem.getPath("/" + entry.getKey())), entry.getKey());
            }
            for (String name : directories) {
                assertTrue(Files.isDirectory(fileSystem.getPath("/" + name)), name);
            }
            try (var paths = Files.walk(fileSystem.getPath("/"))) {
                assertEquals(expected.keySet(), paths.filter(Files::isRegularFile)
                        .map(path -> path.toString().substring(1)).collect(java.util.stream.Collectors.toSet()));
            }
        }
        if (!split) {
            var observed = new HashSet<String>();
            try (var reader = ZipArkivoStreamingReader.open(archive, options)) {
                while (reader.next()) {
                    var attributes = reader.readAttributes();
                    String name = attributes.path().replace('\\', '/');
                    assertTrue(observed.add(name), "Duplicate streaming path: " + name);
                    if (attributes.isDirectory()) {
                        assertTrue(directories.contains(name), name);
                    } else {
                        byte @Nullable [] body = expected.get(name);
                        assertNotNull(body, name);
                        try (var input = reader.openInputStream()) {
                            assertArrayEquals(body, input.readAllBytes(), name);
                        }
                    }
                }
            }
            assertEquals(expected.size() + directories.size(), observed.size());
        }
    }

    /// Selects credentials by logical entry name and configures the explicit legacy name charset.
    private static ZipArchiveOptions.Read readOptions(Charset charset, Map<String, String> passwords) {
        return ZipArchiveOptions.READ_DEFAULTS.withLegacyMetadataDecoder(ArchiveMetadataDecoder.forCharset(charset))
                .withPasswordProvider(request -> passwords.getOrDefault(
                        Objects.requireNonNull(request.entryPath()).substring(1), passwords.getOrDefault("*", ""))
                        .getBytes(StandardCharsets.UTF_8));
    }

    /// Resolves a source file from the verified upstream resource directory.
    private static Path content(String name) {
        return resources().resolve("test-files").resolve(name);
    }

    /// Resolves an archive from the verified upstream resource directory.
    private static Path archive(String name) {
        return resources().resolve("test-archives").resolve(name);
    }

    /// Returns the resource root prepared by Gradle without modifying its files.
    private static Path resources() {
        return Path.of(Objects.requireNonNull(System.getProperty("arkivo.zip4j.testDataDirectory")))
                .resolve("src/test/resources");
    }
}
